# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95a47a60919100d835c3a971a5e67ebabbb9299e8b201df40e5444e6c4a1606fe029f27bc232991de186e11ef313ce00f7bc9a68e5b7971a6a05fe2687fdef76

test:
  secret_key_base: af1b916fa8ee94d7788c4a71165ead37f4996d7f635d07a8c37d45947f0a9e7cceb708fa2c92335357eef651318eed0794b6a0f7aeed4e6628439b4387da0806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
